BazaLekow_BAS/Controllers/AdminsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BazaLekow_BAS.Models.ViewModel;
using BazaLekow_BAS.Models;
using BazaLekow_BAS.Utility;
using BazaLekow_BAS.Models.Services;

namespace BazaLekow_BAS.Controllers
{
    [AuthorizationFilter]
    public class AdminsController : Controller
    {
        private IAdminService service;

        public AdminsController(IAdminService service)
        {
            this.service = service;
        }

        // GET: Admins
        public ActionResult Index()
        {
            var admins = service.GetAll().ToList();
            List<AdminViewModel> aView = new List<AdminViewModel>(admins.Count);
            for(int i = 0; i < admins.Count; ++i)
            {
                aView.Add(new AdminViewModel(admins[i]));
            }

            return View(aView);
        }

        // GET: Admins
        public JsonResult IndexJSON()
        {
            var admins = service.GetAll().ToList();
            List<AdminViewModel> aView = new List<AdminViewModel>(admins.Count);
            for (int i = 0; i < admins.Count; ++i)
            {
                aView.Add(new AdminViewModel(admins[i]));
            }

            return Json(aView, JsonRequestBehavior.AllowGet);
        }

        // GET: Admins/Details/5
        [HttpGet]
        public JsonResult DetailsJSON(int? id)
        {
            if (id == null)
            {
                return Json("Success", JsonRequestBehavior.AllowGet);
            }
            Admin admin = service.Get(id.Value);
            AdminViewModel a = new AdminViewModel(admin);
            if (admin == null)
            {
                return Json("Błąd", JsonRequestBehavior.AllowGet);
            }

            return Json(a, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        [ValidateAntiForgeryHeader]
        public JsonResult CreateJSON([Bind(Include = "Username,Password")] AdminViewModel admin)
        {
            if (ModelState.IsValid)
            {
                Admin a = new Admin();
                a.username = admin.Username;
                a.password = Utility.Utility.hashPassword(admin.Password);
                service.Add(a);
                return Json("Success", JsonRequestBehavior.AllowGet);
            }

            return Json("Błąd", JsonRequestBehavior.AllowGet);
        }
  



        [HttpPost]
        [ValidateAntiForgeryHeader]
        public JsonResult EditJSON([Bind(Include = "Id,Username,Password")] AdminViewModel admin)
        {
            if(admin == null && admin.Username == "" || admin.Id == 0)
                return Json("Błąd", JsonRequestBehavior.AllowGet);

            if (ModelState.IsValid)
            {
                Admin old = service.Get(admin.Id);
                if(old.username != admin.Username)
                    old.username = admin.Username;
                if (admin.Password != null)
                    old.password = Utility.Utility.hashPassword(admin.Password);

                service.Update(old);
                return Json("Success", JsonRequestBehavior.AllowGet);
            }

            return Json("Błąd", JsonRequestBehavior.AllowGet);
        }



        // POST: Admins/Delete/5
        [HttpPost]
        [ValidateAntiForgeryHeader]
        public JsonResult DeleteJSON(int? id)
        {
            if(id == null)
                return Json("Błąd", JsonRequestBehavior.AllowGet);

            service.Delete(id.Value);
            return Json("Success", JsonRequestBehavior.AllowGet);
        }
    }
}

BazaLekow_BAS/Controllers/DrugsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BazaLekow_BAS.Models;
using BazaLekow_BAS.Utility;
using BazaLekow_BAS.Models.Services;
using BazaLekow_BAS.Models.ViewModel;

namespace BazaLekow_BAS.Controllers
{
    [AuthorizationFilter]
    public class DrugsController : Controller
    {
        private IDrugService service;

        public DrugsController(IDrugService service)
        {
            this.service = service;
        }

        // GET: Drugs
        public ActionResult Index()
        {
            return View(service.GetSmallDrugs().ToList());
        }

        // GET: Drugs Json
        public JsonResult IndexJSON()
        {
            return Json(service.GetSmallDrugs().ToList(), JsonRequestBehavior.AllowGet);
        }

        [AllowAnonymous]
        // GET: Drugs Guest
        public ActionResult Guest()
        {
            return View(service.GetSmallDrugs().ToList());

        }

        [AllowAnonymous]
        // GET: Drugs Guest Json
        public JsonResult GuestJSON()
        {
            return Json(service.GetSmallDrugs().ToList(), JsonRequestBehavior.AllowGet);
        }

        [AllowAnonymous]
        // GET: Drugs/Details/id
        public JsonResult DetailsGuestJSON(int? id)
        {
            if(id == null)
            {
                return Json("Nieznana wartość", JsonRequestBehavior.AllowGet);
            }

            return Json(service.GetWholeData(id.Value), JsonRequestBehavior.AllowGet);
        }

        
        [HttpPost]
        [ValidateAntiForgeryHeader]
        //public JsonResult CreateJSON(DrugSmallViewModel drug, DrugDataViewModel drugData, DrugProductViewModel[] products, [Bind(Include = "Ingredients")] IngredientSmallViewModel[] ingredients)
        public JsonResult CreateJSON(DrugWholeDataSetViewModel drug)
        {
            if(drug == null || drug.Name == null)
            {
                return Json("Błąd", JsonRequestBehavior.AllowGet);
            }
            if (ModelState.IsValid)
            {
                service.Add(drug);
                return Json("Success", JsonRequestBehavior.AllowGet);
            }

            return Json("Błąd", JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        [ValidateAntiForgeryHeader]
        public ActionResult EditJSON(DrugWholeDataSetViewModel drug)
        {
            if (drug == null || drug.Name == null)
            {
                return Json("Błąd", JsonRequestBehavior.AllowGet);
            }
            if (ModelState.IsValid)
            {
                service.Update(drug);
                return Json("Success", JsonRequestBehavior.AllowGet);
            }

            return Json("Błąd", JsonRequestBehavior.AllowGet);
        }

        // POST: Drugs/Delete/5
        [HttpPost]
        [ValidateAntiForgeryHeader]
        public ActionResult DeleteJSON(int? id)
        {
            if(id == null)
                return Json("Błąd", JsonRequestBehavior.AllowGet);

            service.Delete(id.Value);
            return Json("Success", JsonRequestBehavior.AllowGet);
        }
    }
}

BazaLekow_BAS/Controllers/IngredientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BazaLekow_BAS.Models;
using BazaLekow_BAS.Utility;
using BazaLekow_BAS.Models.Services;
using BazaLekow_BAS.Models.ViewModel;

namespace BazaLekow_BAS.Controllers
{
    [AuthorizationFilter]

    public class IngredientsController : Controller
    {
        private IIngredientService service;

        public IngredientsController(IIngredientService service)
        {
            this.service = service;
        }

        // GET: Ingredients
        public ActionResult Index()
        {
            return View(service.GetSmallIngredients().ToList());
        }

        public JsonResult IndexJSON()
        {
            return Json(service.GetSmallIngredients().ToList(), JsonRequestBehavior.AllowGet);
        }

        [AllowAnonymous]
        // GET: Ingredients Guest
        public ActionResult Guest()
        {
            return View(service.GetSmallIngredients().ToList());
        }

        [AllowAnonymous]
        // GET: Ingredients Guest
        public JsonResult GuestJSON()
        {
            return Json(service.GetSmallIngredients().ToList(), JsonRequestBehavior.AllowGet);
        }

        [AllowAnonymous]
        // GET: Ingredients/Details/5
        public JsonResult DetailsGuestJSON(int? id)
        {
            if (id == null)
            {
                return Json("Złe id", JsonRequestBehavior.AllowGet);
            }

            return Json(service.GetWholeData(id.Value), JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        [ValidateAntiForgeryHeader]

        public JsonResult CreateJSON([Bind(Include = "id,name")] IngredientSmallViewModel ingredient,[Bind(Include = "effects,indications,contradictions,interactions,side_effects,pregnancy,dosage,comments,other")] IngredientDataViewModel data)
        {
            if (ingredient == null || data == null)
                return Json("Błąd", JsonRequestBehavior.AllowGet);
            if (ModelState.IsValid)
            {
                service.Add(ingredient.ToIngredient(), data.ToIngredientData());
                return Json("Błąd", JsonRequestBehavior.AllowGet);
            }

            return Json("Błąd", JsonRequestBehavior.AllowGet);
        }

        
        [HttpPost]
        [ValidateAntiForgeryHeader]
        public JsonResult EditJSON([Bind(Include = "id,name")] IngredientSmallViewModel ingredient, [Bind(Include = "effects,indications,contradictions,interactions,side_effects,pregnancy,dosage,comments,other")] IngredientDataViewModel data)
        {
            if (ingredient == null || data == null)
                return Json("Błąd", JsonRequestBehavior.AllowGet);

            if (ModelState.IsValid)
            {
                var oldIngredient = service.Get(ingredient.Id);
                var oldData = service.GetData(oldIngredient.data_id);
                oldIngredient.name = ingredient.Name;
                oldData.comments = data.Comments;
                oldData.contradictions = data.Contradictions;
                oldData.dosage = data.Dosage;
                oldData.effects = data.Effects;
                oldData.indications = data.Indications;
                oldData.interactions = data.Interactions;
                oldData.other = data.Other;
                oldData.pregnancy = data.Pregnancy;
                oldData.side_effects = data.Side_effects;

                service.Update(oldIngredient, oldData);
                return Json("Success", JsonRequestBehavior.AllowGet);
            }

            return Json("Błąd", JsonRequestBehavior.AllowGet);
        }
        

        
        // POST: Ingredients/Delete/5
        [HttpPost]
        [ValidateAntiForgeryHeader]
        public JsonResult DeleteJSON(int? id)
        {
            if(id == null)
                return Json("Błąd", JsonRequestBehavior.AllowGet);

            service.Delete(id.Value);
            return Json("Success", JsonRequestBehavior.AllowGet);
        }
    }
}

BazaLekow_BAS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html  ng-app="MyApp"  ng-cloak>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <form id="antiForgeryForm">
        @Html.AntiForgeryToken()
    </form>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @if (Session["isAuthorized"] != null && Session["username"] != null)
                {
                    @Html.ActionLink("Baza Leków", "Index", "Drugs", new { area = "" }, new { @class = "navbar-brand" })
                }
                else
                {
                    @Html.ActionLink("Baza Leków", "Guest", "Drugs", new { area = "" }, new { @class = "navbar-brand" })
                }
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Session["isAuthorized"] != null && Session["username"] != null)
                    {
                        <li>@Html.ActionLink("Baza substancji", "Index", "Ingredients")</li>
                        <li>@Html.ActionLink("Administratorzy", "Index", "Admins")</li>
                        <li ng-controller="LoginController" ng-click="Logout()">
                            <a href="">Wyloguj</a>
                        </li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Baza Substancji", "Guest", "Ingredients")</li>
                        <li ng-controller="LoginController" ng-click="showModal()">
                            <a href="">Zaloguj</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()

    </div>


    <div class="modal fade" id="loginModal" tabindex="1" role="dialog" aria-hidden="true" ng-controller="LoginController">
        <div class="modal-dialog-login">
            <div class="modal-content-login">
                <form novalidate name="f1" ng-submit="Login()" ng-cloak>
                    <table class="loginmodal" ng-show="!IsLogedIn" align="center">
                        <tr ng-show="Message" >
                            <td colspan="0" style="border: none; text-align:center; color:#83e8ee; font-size:1.1em;">{{Message}}</td>
                        </tr>
                        <tr>
                            <td>Username : </td>
                            <td>
                                <input type="text" ng-model="LoginData.Username" name="cUsername" ng-class="Submitted?'ng-dirty':''" required autofocus />
                                <span class="error" ng-show="(f1.cUsername.$dirty || Submitted) && f1.cUsername.$error.required">Username required</span>
                            </td>
                        </tr>
                        <tr>
                            <td>Password : </td>
                            <td>
                                <input type="password" ng-model="LoginData.Password" name="cPassword" ng-class="Submitted?'ng-dirty':''" required autofocus />
                                <span class="error" ng-show="(f1.cPassword.$dirty || Submitted) && f1.cPassword.$error.required">Password required</span>
                            </td>
                        </tr>
                        

                        <tr ng-show="">
                            <td>Password : </td>
                        </tr>
                        <tr >
                            <td align="center">
                                <button type="submit">Zaloguj</button>
                            </td>

                            <td align="center">
                                <button type="button" ng-click="closeModal()">Zamknij</button>
                            </td>
                        </tr>
                    </table>
                </form>
                </div>
            </div>
        </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/angular")
    @Scripts.Render("~/bundles/ui-bootstrap")




   <script src="~/Scripts/MyApp.js"></script>
    @*<script type="text/javascript">
        window.RootUrl = '@Url.Content("~/")';
    </script>*@
    <script src="~/Scripts/AngularControllers/Login.js"></script>
    <script src="~/Scripts/autoheight.js"></script>


    @RenderSection("scripts", required: false)

    <style>
        .modal {
          text-align: center;
          padding: 0!important;
        }

        .modal:before {
          content: '';
          display: inline-block;
          height: 100%;
          vertical-align: middle;
          margin-right: -4px; /* Adjusts for spacing */
        }

        .modal-dialog {
          display: inline-block;
          text-align: left;
          vertical-align: middle;
        }

        .loginmodal, .loginmodal td, .loginmodal tr{
            margin: 0px 0px; 
            border: 1px solid #1F2739;
            padding: 20px
        }

        .loginmodal td:not(:first-child){
            border: 0px solid #1F2739;
        }

        .loginmodal tr:last-child, .loginmodal tr:last-child td{
            padding: 0px;
        }

        .modal-dialog-login{
          width:auto;
           display: inline-block;
          text-align: left;
          vertical-align: middle;
        }
    

        input {
            padding: 5px;
            border: 1px solid #A5A5A5;
        }

            input.ng-dirty.ng-invalid {
                border: 1px solid #83e8ee;
            }

        .error {
            color: #83e8ee;
        }


         .navbar{
        background-color: #191f2c;
        color:#1F2739;
    }
         
        button{
            background-color:#191f2c; 
            color:#83e8ee ;
            text-align: center;
            text-decoration: none; 
            border-color:#141926 ; 
            padding:9px 9px;
            margin:8px 8px
        }

        input{
            background-color:#191f2c; 
            color:#83e8ee ;
            text-align: center;
            text-decoration: none; 
            border-color:#141926 ; 
            padding:9px 9px;
        }
        body, .modal-content, textarea{
            font-family: 'Open Sans', sans-serif;
            font-weight: 300;
            line-height: 1.42em;
            color: #A7A1AE;
            background-color: #1F2739;
            
        }

        textarea{
            resize:vertical;
            max-width:100%;
            width:100%;
            border:none;
            overflow:hidden;
            background-color: #323C50;
        }

        .modal-content-login{
            font-family: 'Open Sans', sans-serif;
            font-weight: 300;
            line-height: 1.42em;
            color: #A7A1AE;
            background-color: #323C50;
        }
        
  
        h1 {
            font-size: 3em;
            font-weight: 300;
            line-height: 1em;
            text-align: center;
            color: #83e8ee;
        }

        h2{
            font-size: 2em;
            font-weight: 300;
            text-align: Left;
            display: block;
            line-height: 1em;
            color: #83e8ee;
        }

            h2 a {
                font-weight: 700;
                text-transform: uppercase;
                color: #83e8ee;
                text-decoration: none;
            }

        .blue {
            color: #185875;
        }

        .yellow {
            color: #FFF842;
        }

        .tableData th h1, .tableDataDetail th h1  {
            font-weight: bold;
            font-size: 1em;
            text-align: left;
            color: #83e8ee;
        }

        .tableData td, .tableDataDetail td {
            font-weight: normal;
            font-size: 1em;
            -webkit-box-shadow: 0 2px 2px -2px #0E1119;
            -moz-box-shadow: 0 2px 2px -2px #0E1119;
            box-shadow: 0 2px 2px -2px #0E1119;
            border: 1px solid #1F2739;
        }

        .tableData, .tableDataDetail {
            text-align: left;
            overflow: hidden;
            width: 100%;
            margin: 0 auto;
            display: table;
            padding: 0 0 8em 0;
        }

            .tableData td, .container th, .tableDataDetail td {
                padding-bottom: 2%;
                padding-top: 2%;
                padding-left: 2%;
            }

            .tableDataDetail td{
                text-align: justify;
                padding: 10px;
            }


            /* Background-color of the odd rows */
            .tableData tr:nth-child(odd) {
                background-color: #323C50;
            }

            .tableDataDetail tr:nth-child(odd) {
                color: #83e8ee;
                font-size: 1.2em;
                background-color: #2C3446;
                box-shadow: #1a1f2a 2px 2px;
            }

            .tableDataDetail .tableDataProduct tr:nth-child(odd) {
                color: #A7A1AE;
                font-size: 1em;
                background-color: #2C3446;
                box-shadow: none;
            }

            .tableDataDetail .tableDataProduct tr:first-child {
                color: #83e8ee;
                font-size: 1.2em;
                background-color: #2C3446;
                box-shadow: #1a1f2a 2px 2px;
            }

            .tableDataDetail .tableDataProduct td:first-child {
                color: #83e8ee;
            }

            .tableData tr:nth-child(even), .tableDataDetail tr:nth-child(even){
                background-color: #323C50;
                
            }

            /* Background-color of the even rows */
            .tableData tr:nth-child(even){
                background-color: #2C3446;
            }

            .tableData th {
                background-color: #1F2739;
            }

            .tableData td:first-child  {
                color: #83e8ee;
            }

            .tableData tr:not(:first-child):hover {
                cursor:pointer;
                background-color: rgba(0, 0, 0, 0.4);
                font-weight: bold;
                box-shadow: rgba(0, 0, 0, 0.4) -1px 1px, rgba(0, 0, 0, 0.4) -2px 2px, rgba(0, 0, 0, 0.4) -3px 3px, rgba(0, 0, 0, 0.4) -4px 4px, rgba(0, 0, 0, 0.4) -5px 5px, rgba(0, 0, 0, 0.66) -6px 6px;
                transform: translate3d(6px, -6px, 0);
                transition-delay: 0s;
                transition-duration: 0.4s;
                transition-property: all;
                //transition-timing-function: line;
            }       
    </style>
</body>
</html>